config/routes.rb
Rails.application.routes.draw do
  
  # 商家会员登录
  get '/account/more_profile' => 'members#more_profile', as: :more_profile
  get '/account/studio' => 'members#studio', as: :new_studio
  get '/account/company' => 'members#company', as: :new_company
  
  resources :studios, only: [:create]
  resources :companies, only: [:create]
  
  # root 'home#index'
  
  # 商家后台
  namespace :portal, path: '' do
    root 'home#index'
    resources :products
    resources :members, path: 'staffs'
    resources :roles, except: :show
    resources :customers
  end
  
  mount RedactorRails::Engine => '/redactor_rails'
  
  # 网页文档
  resources :pages, path: :p, only: [:show]
  
  # 后台系统登录
  devise_for :admins, ActiveAdmin::Devise.config
  # 后台系统路由
  ActiveAdmin.routes(self)
  
  devise_for :members, path: "account", controllers: {
    registrations: :account,
    sessions: :sessions,
  }
  
  # 队列后台管理
  require 'sidekiq/web'
  # require 'sidekiq/cron/web'
  authenticate :admin do
    mount Sidekiq::Web => 'sidekiq'
  end
  
  # API 文档
  mount GrapeSwaggerRails::Engine => '/apidoc'
  
  # API 路由
  mount API::Dispatch => '/api'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :member, foreign_key: 'owner_id'
  
  validates :name, :body, :image, :market_price, :discount_price, :photos_quantity, :owner_id, presence: true
  validates_numericality_of :market_price, :discount_price, :photos_quantity, :stock, only_integer: true, greater_than_or_equal_to: 0
  mount_uploader :image, ImageUploader
  
  scope :sorted, -> { order('sort asc') }
  scope :recent, -> { order('id desc') }
  
  before_create :generate_pid
  def generate_pid
    begin
      n = rand(10)
      if n == 0
        n = 8
      end
      self.pid = n.to_s + SecureRandom.random_number.to_s[2..8]
    end while self.class.exists?(:pid => pid)
  end
  
end

# t.string :pid
# t.string :name,   null: false
# t.string :intro
# t.text   :body,   null: false
# t.string :image,  null: false
# t.integer :price, null: false
# t.integer :discount_price, null: false
# t.integer :stock
# t.integer :view_count, default: 0
# t.integer :orders_count, default: 0
# t.integer :photos_quantity, null: false
# t.string :owner_id, null: false

app/controllers/portal/application_controller.rb
class Portal::ApplicationController < ApplicationController
  include Pundit
  
  layout 'portal'
  
  before_filter :require_member
  before_filter :check_member
  before_filter :check_more_profile
  
  rescue_from Pundit::NotAuthorizedError, with: :unauthorized
  
  private
  
  alias_method :pundit_user, :current_member
  
  def unauthorized
    redirect_to request.referrer || portal_root_path, alert: '没有权限执行！'
  end
  
end

app/controllers/portal/customers_controller.rb
class Portal::CustomersController < Portal::ApplicationController
  before_action :set_customer, only: [:show, :edit, :destroy]
  
  def index
    authorize Customer
    @page_header = "客户列表"
    @action = new_portal_customer_path
    @customers = policy_scope(Customer).paginate page: params[:page], per_page: 30
  end
  
  def show
    @page_header = "客户详情"
  end
  
  def new
    @page_header = "新建客户"
    @customer = Customer.new
    authorize @customer
  end
  
  def create
    @customer = Customer.new(customer_params)
    authorize @customer
    @customer.owner_id = current_member.account.id
    if @customer.save
      flash[:success] = '创建成功'
      redirect_to portal_customers_url
    else
      # puts @product.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新客户资料"
  end
  
  def update
    @customer = Customer.find_by(owner_id: current_member.account.id, id: params[:id])
    
    if @customer.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_customers_url
      return
    end
    
    authorize @customer
    
    if @customer.update(customer_params)
      flash[:success] = '更新成功'
      redirect_to portal_customers_url
    else
      render :edit
    end
  end
  
  def destroy
    @customer.destroy
    flash[:success] = '删除成功'
    redirect_to portal_customers_url
  end
  
  private
  def set_customer    
    @customer = Customer.find_by(owner_id: current_member.account.id, o_id: params[:id])
    
    if @customer.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_customers_url
      return
    end
    
    authorize @customer
  end
  
  def customer_params
    params.require(:customer).permit(:avatar, :nickname, :realname, :mobile, :address)
  end
end

app/controllers/portal/home_controller.rb
class Portal::HomeController < Portal::ApplicationController
  
  def index
    @page_header = "控制面板"
  end
end

app/controllers/portal/members_controller.rb
class Portal::MembersController < Portal::ApplicationController
  
  def index
    authorize Member
    @page_header = "账户列表"
    @action = new_portal_member_path
    @members = policy_scope(Member).includes(:roles).paginate page: params[:page], per_page: 30
  end
  
  def show
    @page_header = "账户详情"
    # @product = Product.find_by(pid: params[:id])
  end
  
  def new
    @page_header = "新建账户"
    @member = Member.new
    authorize @member
  end
  
  def create
    @member = Member.new(member_params)
    authorize @member
    @member.parent_id = current_member.id
    @member.account_type = Member::ACCOUNT_TYPE_STAFF
    if @member.save
      flash[:success] = '创建成功'
      redirect_to portal_members_url
    else
      render :new
    end
  end
  
  def edit
    @page_header = "更新产品"
    begin
      @member = current_member.staffs.find(params[:id])
      authorize @member
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = '记录不存在'
      redirect_to portal_members_path
    end
  end
  
  def update
    # @member = current_member.staffs.find(params[:id])
    # authorize @member
    begin
      @member = current_member.staffs.find(params[:id])
      authorize @member
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = '记录不存在'
      redirect_to portal_members_path
    end
    
    if @member.update(member_params)
      flash[:success] = '更新成功'
      redirect_to portal_members_url
    else
      render :edit
    end
  end
  
  def destroy
    # @member = current_member.staffs.find(params[:id])
    # authorize @member
    begin
      @member = current_member.staffs.find(params[:id])
      authorize @member
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = '记录不存在'
      redirect_to portal_members_path
    end
    
    unless @member.destroy
      flash[:alert] = @member.errors.full_messages.join(',')
    end
    redirect_to portal_members_url
  end
  
  private
  def member_params
    params.require(:member).permit(:mobile, :password, :password_confirmation, role_ids: [])
  end
end

app/controllers/portal/products_controller.rb
class Portal::ProductsController < Portal::ApplicationController
  before_action :set_product, only: [:show, :edit, :destroy]
  
  def index
    authorize Product
    @page_header = "产品列表"
    @action = new_portal_product_path
    @products = policy_scope(Product).paginate page: params[:page], per_page: 30
  end
  
  def show
    @page_header = "产品详情"
  end
  
  def new
    @page_header = "新建产品"
    @product = Product.new
    authorize @product
  end
  
  def create
    @product = Product.new(product_products)
    authorize @product
    @product.owner_id = current_member.admin? ? current_member.id : current_member.parent_id
    if @product.save
      flash[:success] = '创建成功'
      redirect_to portal_products_url
    else
      # puts @product.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新产品"
  end
  
  def update
    if current_member.admin?
      @product = Product.find_by(owner_id: current_member.id, id: params[:id])
    else
      @product = Product.find_by(owner_id: current_member.parent_id, id: params[:id])
    end
    
    if @product.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_products_url
      return
    end
    
    authorize @product
    
    if @product.update(product_products)
      flash[:success] = '更新成功'
      redirect_to portal_products_url
    else
      render :edit
    end
  end
  
  def destroy
    @product.destroy
    flash[:success] = '删除成功'
    redirect_to portal_products_url
  end
  
  private
  def set_product
    if current_member.admin?
      @product = Product.find_by(owner_id: current_member.id, pid: params[:id])
    else
      @product = Product.find_by(owner_id: current_member.parent_id, pid: params[:id])
    end
    
    if @product.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_products_url
      return
    end
    
    authorize @product
  end
  
  def product_products
    params.require(:product).permit(:name, :intro, :body, :image, :stock, :sort, :market_price, :discount_price, :photos_quantity)
  end
end

app/controllers/portal/roles_controller.rb
class Portal::RolesController < Portal::ApplicationController
  
  def index
    @page_header = "角色列表"
    authorize Role
    @action = new_portal_role_path
    @roles = policy_scope(Role).paginate page: params[:page], per_page: 30
  end
  
  def new
    @page_header = "新建产品"
    @role = Role.new
    authorize @role
  end
  
  def create
    @role = Role.new(role_params)
    authorize @role
    @role.owner_id = current_member.id
    puts @role.name
    if @role.save
      flash[:success] = '创建成功'
      redirect_to portal_roles_url
    else
      # flash.now.alert = @role.errors.full_messages.join(',')
      # puts @role.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新角色"
    
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    # @role = Role.find(params[:id])
    authorize @role
  end
  
  def update
    # @role = Role.find(params[:id])
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    authorize @role
    if @role.update(role_params)
      flash[:success] = '更新成功'
      redirect_to portal_roles_url
    else
      render :edit
    end
  end
  
  def destroy
    # @role = Role.find(params[:id])
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    authorize @role
    @role.destroy
    redirect_to portal_roles_url
  end
  
  private
  def role_params
    role_params = params.require(:role).permit(:name, permissions: [])
    role_params[:permissions] = build_permissions(role_params[:permissions] || [])
    role_params
  end
  
  def build_permissions(permissions)
    # puts permissions
    parse_permissions(permissions).collect do |permission|
      if @role.nil?
        Permission.new(permission)
      else
        @role.permissions.find_or_initialize_by(permission)
      end
    end
  end
  
  def parse_permissions(permissions)
    permissions.collect do |permission|
      action, resource = permission.split('#', 2)
      { action: action, resource: resource }
    end
  end
  
end

app/views/portal/products/_form.html.erb
<div class="x_panel">
  <div class="x_content">
    <br />
    
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    
        <%= simple_form_for([:portal, @product], html: { class: 'form-horizontal form-label-left', id: 'product_form' },
          wrapper: :horizontal_form,
          wrapper_mappings: {
            check_boxes: :horizontal_radio_and_checkboxes,
            radio_buttons: :horizontal_radio_and_checkboxes,
            file: :horizontal_file_input,
            boolean: :horizontal_boolean
          }) do |f| %>
            <%= f.input :name %>
            <%= f.input :image, hint: '图片格式为：jpg, jpeg, png；图片尺寸为：750x512' %>
            <%= f.input :intro %>
            <%= f.input :body, as: :text, input_html: { class: 'redactor' },placeholder: '网页内容，支持图文混排', hint: '网页内容，支持图文混排' %>
            <%= f.input :market_price, placeholder: '大于或等于0的整数' %>
            <%= f.input :discount_price, placeholder: '大于或等于0的整数' %>
            <%= f.input :photos_quantity, placeholder: '大于或等于0的整数' %>
            <%= f.input :stock, placeholder: '大于或等于0的整数' %>
            <%= f.input :sort, hint: '值越小，显示越靠前' %>
            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <%= link_to '取消', :back, class: "btn btn-primary" %>
                <button type="submit" class="btn btn-success"><%= f.object.new_record? ? "新建产品" : "更新产品" %></button>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/portal/products/_product.html.erb
<tr>
  <td><%= link_to image_tag(product.image.url(:small)), portal_product_path(product.pid) %></td>
  <td><%= product.pid %></td>
  <td><%= product.name %></td>
  <td><%= product.market_price %></td>
  <td><%= product.discount_price %></td>
  <td><%= product.photos_quantity %></td>
  <td><%= product.stock %></td>
  <td>
    <%= link_to '编辑', edit_portal_product_path(product.pid), class: 'btn btn-sm btn-default' if policy(Product).update? %>
    <%= link_to '删除', portal_product_path(product.pid), method: :delete,  data: { confirm: '您确定吗？' },class: 'btn btn-sm btn-danger' if policy(Product).destroy? %>
  </td>
</tr>

app/views/portal/products/edit.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>编辑产品</h3>
  </div>
</div>

<div class="clearfix"></div>

<%= render 'form' %>

app/views/portal/products/index.html.erb
<% content_for :styles do %>
<%= stylesheet_link_tag  'products' %>
<% end %>

<div class="page-title">
  <div class="title_left">
    <h3>产品列表</h3>
  </div>

  <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="输入产品名称">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">搜索</button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="clearfix"></div>

<% if @products.empty? %>
<div class="x_panel">
  <div class="x_content">
    <div class="no-results"><无数据显示><br /><%= link_to '新建产品', @action, class: 'btn btn-primary' %></div>
  </div>
</div>
<% else %>            
<div class="x_panel">
  <div class="x_content">
    <div class="content-list">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>缩略图</th>
            <th>产品ID</th>
            <th>产品名</th>
            <th>原价</th>
            <th>折扣价</th>
            <th>照片数量</th>
            <th>库存</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @products %>
        </tbody>
      </table>
    </div>
  </div>
  <div style="text-align: center;"><%= will_paginate @products, renderer: BootstrapPagination::Rails %></div>
</div>

<% end %>

app/views/portal/products/new.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>新建产品</h3>
  </div>
</div>

<div class="clearfix"></div>

<%= render 'form' %>

app/views/portal/products/show.html.erb
<div class="row well">
  <div class="col-md-4">产品图片</div>
  <div class="col-md-8"><%= image_tag @product.image.url(:thumb) %></div>
  
  <div class="col-md-4">产品ID</div>
  <div class="col-md-8"><%= @product.pid %></div>
  
  <div class="col-md-4">产品名称</div>
  <div class="col-md-8"><%= @product.name %></div>
  
  <div class="col-md-4">产品简介</div>
  <div class="col-md-8"><%= @product.intro %></div>
  
  <div class="col-md-4">产品详情</div>
  <div class="col-md-8"><%= @product.body %></div>
  
  <div class="col-md-4">产品原价</div>
  <div class="col-md-8"><%= @product.market_price %></div>
  
  <div class="col-md-4">产品折扣价</div>
  <div class="col-md-8"><%= @product.discount_price %></div>
  
  <div class="col-md-4">产品库存</div>
  <div class="col-md-8"><%= @product.stock %></div>
  
  <div class="col-md-4">创建日期</div>
  <div class="col-md-8"><%= @product.created_at.strftime('%Y-%m-%d %H:%M:%S') %></div>
</div>