config/routes.rb
Rails.application.routes.draw do
  
  # 商家会员登录
  get '/account/more_profile' => 'members#more_profile', as: :more_profile
  get '/account/studio' => 'members#studio', as: :new_studio
  get '/account/company' => 'members#company', as: :new_company
  
  resources :studios, only: [:create]
  resources :companies, only: [:create]
  
  # root 'home#index'
  
  # 商家后台
  namespace :portal, path: '' do
    root 'home#index'
    resources :products
    resources :members, path: 'staffs'
    resources :roles, except: :show
    resources :customers
  end
  
  mount RedactorRails::Engine => '/redactor_rails'
  
  # 网页文档
  resources :pages, path: :p, only: [:show]
  
  # 后台系统登录
  devise_for :admins, ActiveAdmin::Devise.config
  # 后台系统路由
  ActiveAdmin.routes(self)
  
  devise_for :members, path: "account", controllers: {
    registrations: :account,
    sessions: :sessions,
  }
  
  # 队列后台管理
  require 'sidekiq/web'
  # require 'sidekiq/cron/web'
  authenticate :admin do
    mount Sidekiq::Web => 'sidekiq'
  end
  
  # API 文档
  mount GrapeSwaggerRails::Engine => '/apidoc'
  
  # API 路由
  mount API::Dispatch => '/api'
end

app/models/member.rb
class Member < ActiveRecord::Base
  
  ACCOUNT_TYPE_STUDIO  = 1 # 工作室账户
  ACCOUNT_TYPE_COMPANY = 2 # 公司顶级账户
  ACCOUNT_TYPE_STAFF   = 3 # 公司下面的子账户
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:mobile]
         
  mount_uploader :avatar, AvatarUploader
  
  belongs_to :parent, class_name: 'Member', foreign_key: 'parent_id'
  has_many   :staffs, class_name: 'Member', foreign_key: 'parent_id'
  
  # has_many :roles, foreign_key: 'owner_id'
  
  has_and_belongs_to_many :roles, join_table: :roles_staffs, class_name: 'Role', foreign_key: 'staff_id'
  # has_and_belongs_to_many :roles, join_table: :roles_staffs, foreign_key: 'staff_id'
  has_many :permissions, through: :roles
  
  attr_accessor :code
  
  validates :mobile, presence: true
  validates :mobile, format: { with: /\A1[3|4|5|8|7][0-9]\d{8}\z/, message: "请输入11位正确手机号" }, length: { is: 11 },:uniqueness => true
  
  before_create :generate_o_id_and_private_token
  def generate_o_id_and_private_token
    begin
      n = rand(10)
      if n == 0
        n = 8
      end
      self.o_id = n.to_s + SecureRandom.random_number.to_s[2..8]
    end while self.class.exists?(:o_id => o_id)
    self.private_token = SecureRandom.uuid.gsub('-', '')
  end
  
  ### 重写devise方法
  def email_required?
    false
  end
  
  def email_changed?
    false
  end
  
  def account
    self.parent_id.blank? ? self : self.parent
  end
  
  # 是否是管理员
  def admin?
    ( (account_type == Member::ACCOUNT_TYPE_STUDIO or account_type == Member::ACCOUNT_TYPE_COMPANY) and parent_id.blank? )
  end
  
  def company?
    admin? and account_type == Member::ACCOUNT_TYPE_COMPANY
  end
         
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  before_filter :require_member
  before_filter :check_member
  
  layout :layout_by_action
  def layout_by_action
    if %w(more_profile studio company).include?(action_name)
      "account"
    elsif %w(new create).include?(action_name)
      "account"
    end
  end
  
  def more_profile
    @action = "完善资料"
  end
  
  def studio
    @action = "工作室"
    @studio = Studio.new
  end
  
  def company
    @action = "影楼"
    @company = Company.new
  end
end

app/controllers/portal/application_controller.rb
class Portal::ApplicationController < ApplicationController
  include Pundit
  
  layout 'portal'
  
  before_filter :require_member
  before_filter :check_member
  before_filter :check_more_profile
  
  rescue_from Pundit::NotAuthorizedError, with: :unauthorized
  
  private
  
  alias_method :pundit_user, :current_member
  
  def unauthorized
    redirect_to request.referrer || portal_root_path, alert: '没有权限执行！'
  end
  
end

app/controllers/portal/customers_controller.rb
class Portal::CustomersController < Portal::ApplicationController
  before_action :set_customer, only: [:show, :edit, :destroy]
  
  def index
    authorize Customer
    @page_header = "客户列表"
    @action = new_portal_customer_path
    @customers = policy_scope(Customer).paginate page: params[:page], per_page: 30
  end
  
  def show
    @page_header = "客户详情"
  end
  
  def new
    @page_header = "新建客户"
    @customer = Customer.new
    authorize @customer
  end
  
  def create
    @customer = Customer.new(customer_params)
    authorize @customer
    @customer.owner_id = current_member.account.id
    if @customer.save
      flash[:success] = '创建成功'
      redirect_to portal_customers_url
    else
      # puts @product.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新客户资料"
  end
  
  def update
    @customer = Customer.find_by(owner_id: current_member.account.id, id: params[:id])
    
    if @customer.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_customers_url
      return
    end
    
    authorize @customer
    
    if @customer.update(customer_params)
      flash[:success] = '更新成功'
      redirect_to portal_customers_url
    else
      render :edit
    end
  end
  
  def destroy
    @customer.destroy
    flash[:success] = '删除成功'
    redirect_to portal_customers_url
  end
  
  private
  def set_customer    
    @customer = Customer.find_by(owner_id: current_member.account.id, o_id: params[:id])
    
    if @customer.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_customers_url
      return
    end
    
    authorize @customer
  end
  
  def customer_params
    params.require(:customer).permit(:avatar, :nickname, :realname, :mobile, :address)
  end
end

app/controllers/portal/home_controller.rb
class Portal::HomeController < Portal::ApplicationController
  
  def index
    @page_header = "控制面板"
  end
end

app/controllers/portal/members_controller.rb
class Portal::MembersController < Portal::ApplicationController
  
  def index
    authorize Member
    @page_header = "账户列表"
    @action = new_portal_member_path
    @members = policy_scope(Member).includes(:roles).paginate page: params[:page], per_page: 30
  end
  
  def show
    @page_header = "账户详情"
    # @product = Product.find_by(pid: params[:id])
  end
  
  def new
    @page_header = "新建账户"
    @member = Member.new
    authorize @member
  end
  
  def create
    @member = Member.new(member_params)
    authorize @member
    @member.parent_id = current_member.id
    @member.account_type = Member::ACCOUNT_TYPE_STAFF
    if @member.save
      flash[:success] = '创建成功'
      redirect_to portal_members_url
    else
      render :new
    end
  end
  
  def edit
    @page_header = "更新产品"
    begin
      @member = current_member.staffs.find(params[:id])
      authorize @member
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = '记录不存在'
      redirect_to portal_members_path
    end
  end
  
  def update
    # @member = current_member.staffs.find(params[:id])
    # authorize @member
    begin
      @member = current_member.staffs.find(params[:id])
      authorize @member
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = '记录不存在'
      redirect_to portal_members_path
    end
    
    if @member.update(member_params)
      flash[:success] = '更新成功'
      redirect_to portal_members_url
    else
      render :edit
    end
  end
  
  def destroy
    # @member = current_member.staffs.find(params[:id])
    # authorize @member
    begin
      @member = current_member.staffs.find(params[:id])
      authorize @member
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = '记录不存在'
      redirect_to portal_members_path
    end
    
    unless @member.destroy
      flash[:alert] = @member.errors.full_messages.join(',')
    end
    redirect_to portal_members_url
  end
  
  private
  def member_params
    params.require(:member).permit(:mobile, :password, :password_confirmation, role_ids: [])
  end
end

app/controllers/portal/products_controller.rb
class Portal::ProductsController < Portal::ApplicationController
  before_action :set_product, only: [:show, :edit, :destroy]
  
  def index
    authorize Product
    @page_header = "产品列表"
    @action = new_portal_product_path
    @products = policy_scope(Product).paginate page: params[:page], per_page: 30
  end
  
  def show
    @page_header = "产品详情"
  end
  
  def new
    @page_header = "新建产品"
    @product = Product.new
    authorize @product
  end
  
  def create
    @product = Product.new(product_products)
    authorize @product
    @product.owner_id = current_member.admin? ? current_member.id : current_member.parent_id
    if @product.save
      flash[:success] = '创建成功'
      redirect_to portal_products_url
    else
      # puts @product.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新产品"
  end
  
  def update
    if current_member.admin?
      @product = Product.find_by(owner_id: current_member.id, id: params[:id])
    else
      @product = Product.find_by(owner_id: current_member.parent_id, id: params[:id])
    end
    
    if @product.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_products_url
      return
    end
    
    authorize @product
    
    if @product.update(product_products)
      flash[:success] = '更新成功'
      redirect_to portal_products_url
    else
      render :edit
    end
  end
  
  def destroy
    @product.destroy
    flash[:success] = '删除成功'
    redirect_to portal_products_url
  end
  
  private
  def set_product
    if current_member.admin?
      @product = Product.find_by(owner_id: current_member.id, pid: params[:id])
    else
      @product = Product.find_by(owner_id: current_member.parent_id, pid: params[:id])
    end
    
    if @product.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_products_url
      return
    end
    
    authorize @product
  end
  
  def product_products
    params.require(:product).permit(:name, :intro, :body, :image, :stock, :sort, :market_price, :discount_price, :photos_quantity)
  end
end

app/controllers/portal/roles_controller.rb
class Portal::RolesController < Portal::ApplicationController
  
  def index
    @page_header = "角色列表"
    authorize Role
    @action = new_portal_role_path
    @roles = policy_scope(Role).paginate page: params[:page], per_page: 30
  end
  
  def new
    @page_header = "新建产品"
    @role = Role.new
    authorize @role
  end
  
  def create
    @role = Role.new(role_params)
    authorize @role
    @role.owner_id = current_member.id
    puts @role.name
    if @role.save
      flash[:success] = '创建成功'
      redirect_to portal_roles_url
    else
      # flash.now.alert = @role.errors.full_messages.join(',')
      # puts @role.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新角色"
    
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    # @role = Role.find(params[:id])
    authorize @role
  end
  
  def update
    # @role = Role.find(params[:id])
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    authorize @role
    if @role.update(role_params)
      flash[:success] = '更新成功'
      redirect_to portal_roles_url
    else
      render :edit
    end
  end
  
  def destroy
    # @role = Role.find(params[:id])
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    authorize @role
    @role.destroy
    redirect_to portal_roles_url
  end
  
  private
  def role_params
    role_params = params.require(:role).permit(:name, permissions: [])
    role_params[:permissions] = build_permissions(role_params[:permissions] || [])
    role_params
  end
  
  def build_permissions(permissions)
    # puts permissions
    parse_permissions(permissions).collect do |permission|
      if @role.nil?
        Permission.new(permission)
      else
        @role.permissions.find_or_initialize_by(permission)
      end
    end
  end
  
  def parse_permissions(permissions)
    permissions.collect do |permission|
      action, resource = permission.split('#', 2)
      { action: action, resource: resource }
    end
  end
  
end

app/helpers/members_helper.rb
module MembersHelper
  def member_avatar_tag(member, size = :large, img_class = '')
    if member.blank? or member.avatar.blank?
      return image_tag("avatar/#{size}.png", class: img_class)
    end
    
    image_tag(member.avatar.url(size), class: img_class)
    
  end
end

app/views/portal/members/_form.html.erb
<div class="x_panel">
  <div class="x_content">
    <br />
    
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    
        <%= simple_form_for([:portal, @member], html: { class: 'form-horizontal form-label-left', id: 'member_form' },
          wrapper: :horizontal_form,
          wrapper_mappings: {
            check_boxes: :horizontal_radio_and_checkboxes,
            radio_buttons: :horizontal_radio_and_checkboxes,
            file: :horizontal_file_input,
            boolean: :horizontal_boolean
          }) do |f| %>
            <%= f.input :mobile %>
            <% if f.object.new_record? %>
            <%= f.input :password, hint: '密码至少为6位' %>
            <%= f.input :password_confirmation, hint: '密码至少为6位' %>
            <% end %>
            <% if Role.where(owner_id: current_member.id).empty? %>
            <div class="form-group">
              <label class="col-sm-3 control-label">角色</label>
              <div class="col-sm-9">
                <%= link_to '还没有创建角色，现在去创建！', new_portal_role_path, class: 'btn btn-primary' %>
              </div>
            </div>
            <% else %>
            <%= f.input :role_ids, as: :check_boxes, include_hidden: false, collection: Role.where(owner_id: current_member.id).map { |role| [role.name, role.id] } %>
            <% end %>
            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <%= link_to '取消', :back, class: "btn btn-primary" %>
                <button type="submit" class="btn btn-success"><%= f.object.new_record? ? "新建账户" : "编辑账户" %></button>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/portal/members/_member.html.erb
<tr>
  <td><%= member_avatar_tag(member, :normal) %></td>
  <td><%= member.mobile %></td>
  <td><%= member.roles.map(&:name).join(',') %></td>
  <td><%= l member.created_at, format: :long %></td>
  <td>
    <%= link_to '编辑', edit_portal_member_path(member), class: 'btn btn-sm btn-default' %>
    <%= link_to '删除', portal_member_path(member), method: :delete,  data: { confirm: '您确定吗？' },class: 'btn btn-sm btn-danger' %>
  </td>
</tr>

app/views/portal/members/edit.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>编辑账户</h3>
  </div>
</div>

<div class="clearfix"></div>

<%= render 'form' %>

app/views/portal/members/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>账号列表</h3>
  </div>

  <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="输入手机号">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">搜索</button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="clearfix"></div>

<% if @members.empty? %>
  <div class="x_panel">
    <div class="x_content">
      <div class="no-results"><无数据显示><br /><%= link_to '新建账号', @action, class: 'btn btn-primary' %></div>
    </div>
  </div>
<% else %>            
<div class="x_panel">
  <div class="x_content">
    <div class="content-list">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>头像</th>
            <th>手机</th>
            <th>角色</th>
            <th>at</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @members %>
        </tbody>
      </table>
    </div>
  </div>
  <div style="text-align: center;"><%= will_paginate @members, renderer: BootstrapPagination::Rails %></div>
</div>

<% end %>

app/views/portal/members/new.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>新建账户</h3>
  </div>
</div>

<div class="clearfix"></div>

<%= render 'form' %>